name: EternalParkour
author: Oribuin
version: '@version@'
main: xyz.oribuin.eternalparkour.EternalParkour
api-version: '1.13'
description: A parkour plugin times, checkpoints, leaderboards and more.
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
permissions:
  eternalparkour.*:
    description: Gives access to all commands.
    default: op
    children:
      - eternalparkour.use
      - eternalparkour.reload
      - eternalparkour.admin
      - eternalparkour.create
      - eternalparkour.delete
      - eternalparkour.edit
      - eternalparkour.leaderboard
      - eternalparkour.stats