name: EternalParkour
author: Oribuin
version: '@version@'
main: xyz.oribuin.eternalparkour.EternalParkour
api-version: '1.13'
description: A parkour plugin times, checkpoints, leaderboards and more.
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
